name: Compile, Test, and Deploy
# run-name: Flutter App Actions
on: [push]
jobs:
  Run-Flutter-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
